# Generated by Django 3.2.5 on 2023-01-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='User_id',
        ),
        migrations.AddField(
            model_name='post',
            name='Like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='Tag',
            field=models.JSONField(default={'location': '', 'user': []}),
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(db_column='post_user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='instaAPI.user'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='My PlayList', max_length=20)),
                ('Data', models.JSONField(default={'artist': '', 'music': ''})),
                ('user_id', models.ForeignKey(db_column='playlist_user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_user', to='instaAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(help_text='Comment ID', primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=20)),
                ('contents', models.TextField(help_text='Comment contents')),
                ('like', models.IntegerField(default=0)),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='instaAPI.post')),
            ],
        ),
    ]
